# Generated by Django 2.2.2 on 2020-07-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sdt',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
