# Generated by Django 2.2.2 on 2020-07-02 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HoSoUngTuyen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nganh_nghe', models.IntegerField(default=0, null=True)),
                ('vi_tri_mong_muon', models.CharField(default=None, max_length=255, null=True)),
                ('dia_diem_lam_viec', models.CharField(default=None, max_length=255, null=True)),
                ('trinh_do_hoc_van', models.IntegerField(default=0, null=True)),
                ('so_nam_kinh_nghiem', models.IntegerField(default=0, null=True)),
                ('ten_cty_tung_lam', models.CharField(default=None, max_length=255, null=True)),
                ('hinh_thuc_lam_viec', models.IntegerField(default=0, null=True)),
                ('muc_luong_toi_thieu', models.IntegerField(default=0, null=True)),
                ('ten_bang_cap', models.CharField(default=None, max_length=255, null=True)),
                ('don_vi_dao_tao', models.CharField(default=None, max_length=255, null=True)),
                ('chuyen_nganh', models.CharField(default=None, max_length=255, null=True)),
                ('thoi_gian_bat_dau', models.CharField(default=None, max_length=255, null=True)),
                ('thoi_gian_ket_thuc', models.CharField(default=None, max_length=255, null=True)),
                ('loai_tot_nghiep', models.IntegerField(default=0, null=True)),
                ('ngoai_ngu', models.IntegerField(default=0)),
                ('trinh_do_ngoai_ngu', models.IntegerField(default=0)),
                ('ky_nang', models.IntegerField(default=0)),
                ('hon_nhan', models.IntegerField(default=0)),
                ('so_thich', models.CharField(default=None, max_length=255, null=True)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hồ sơ ứng tuyển',
                'verbose_name_plural': 'Hồ sơ ứng tuyển',
            },
        ),
    ]
