# Generated by Django 2.2.2 on 2020-07-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosoungtuyen',
            name='slug',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
